# Generated by Django 3.0 on 2022-04-12 08:04

from django.db import migrations


def migrate_profiles_data(apps, schema_editor):
    OldProfiles = apps.get_model('oc_lettings_site', 'Profile')
    NewProfiles = apps.get_model('app_profiles', 'Profile')
    for old_profile_instance in OldProfiles.objects.all():
        NewProfiles.objects.create(
            user=old_profile_instance.user,
            favorite_city=old_profile_instance.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_profiles_data),
    ]
