version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  heroku: circleci/heroku@1.2.6

# Define jobs we want to run
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.2
    resources_class: small
    steps:
      - checkout
      - restor_cache:
          key: v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Configure environment
          command: |
            python -m venv .venv
      - run:
          name: Upgrade pip
          command: |
            . .venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            . .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Check linting
          command: |
            . .venv/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            pytest --cov=.

workflows:
  complete_deploy:
    jobs:
      - build_and_test
      - docker/publish:
          extra_build_args: '--build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY --build-arg SENTRY_DSN=$SENTRY_DSN'
          image: $DOCKER_LOGIN/oc-lettings
          tag: '$CIRCLE_SHA1,latest'
          requires:
            - build_and_test
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - build_and_test
          filters:
            branches:
              only: master