version: 2.1

jobs:

  build-n-test:
    docker:
      - image: cimg/python:3.10.2
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Initialize venv / Install deps
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Linting
          command: |
            . .venv/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            pytest --cov=.

  containerize:
    machine: true
    # resource_class: medium
    steps:
      - checkout
      - run:
          name: Setup remote docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker build --tag $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1 .
            docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1

  deploy:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Deploy Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  main:
    jobs:
      - build-n-test
      - containerize:
          requires:
            - build-n-test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-n-test
            - containerize
          filters:
            branches:
              only:
                - master